### PR TITLE
feat: icon refresh

### PR DESCRIPTION
**Pull request by daudix-UFO**
Refresh of current icon, it follows [GNOME HIG](https://developer.gnome.org/hig/guidelines/app-icons.html) design and has more interesting look.

Preview

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Alternative variant

image

**Comment by andyholmes** [comment]
Thanks for the contribution, I think this looks really great. That being said, how would you feel about a more public vote on the change?

Maybe you could post the PR on reddit or something like that and get some thumbs up/down? Alternatively, we could open the GitHub discussions and post a poll?

**Comment by daudix-UFO** [comment]
I'm OK with this idea! we can mix GitHub Discussions and Reddit post, Reddit post in r/gnome with asking opinion about new icon with screenshots and a link to GitHub Discussions for voting

**Comment by andyholmes** [comment]
> Edit: as currently GH Discussions are closed, Reddit votes will be enough, no need to open them for one vote

Oops, I opened a poll before reading your edit :) It's [here](https://github.com/GSConnect/gnome-shell-extension-gsconnect/discussions/1483) anyways if you'd like to link to it. I'm sure we can crunch the numbers if there's a few on either side.

**Comment by daudix-UFO** [comment]
I will finish this very soon, any chance this can land in 43 version?

**Comment by andyholmes** [comment]
Has this been updated with the latest changes? If so, we should merge it before @daniellandau rolls the GNOME 43 release.

**Comment by daudix-UFO** [comment]
Yes, I updated it to latest changes, let's merge :D

**Comment by daniellandau** [comment]
Thanks!

**Pull request merged**
