### PR TITLE
WIP: Port to gnome 45

### LINKED ISSUE #1665: GNOME 45 support
### Describe your request

There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

### Proposed solution

_No response_

### Alternatives

_No response_

### GSConnect version

N/A

### Installed from

OS package manager

### GNOME Shell version

_No response_

### Linux distribution/release

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by istvan-derda**
Work in progress on porting to Gnome 45.

closes #1665

### CODE REVIEW

**Comment by andyholmes** [comment]
Sorry, I wish I had seen this a bit earlier, but in case it's not too late: you don't actually have to port anything outside of the GNOME Shell extension to ESModules if you don't want to.

It's good to do, but it's not necessary for the service to use ESModules to work in GNOME 45. If you don't want to do that, it's fine to just focus on `src/extension.js`, `src/prefs.js` and the files in `src/shell/`.

**Comment by retrixe** [comment]
Hey, based on @andyholmes advice, I was able to port the extension to GNOME 45 with everything functional here: https://github.com/retrixe/gnome-shell-extension-gsconnect/tree/feat/gnome-45-support

Would it be okay for me to create a PR and work to continue there? cc @istvan-derda

There are a bunch of other issues porting to GNOME 45 other than ES modules that I encountered and rectified. I also haven't used code from this PR. I could maybe look into porting the remaining service/preferences code to ESM in my spare time as well in separate PRs.

**Comment by istvan-derda** [comment]
> Hey, based on @andyholmes advice, I was able to port the extension to GNOME 45 with everything functional here: https://github.com/retrixe/gnome-shell-extension-gsconnect/tree/feat/gnome-45-support
> 
> Would it be okay for me to create a PR and work to continue there? cc @istvan-derda
> 
> There are a bunch of other issues porting to GNOME 45 other than ES modules that I encountered and rectified. I also haven't used code from this PR. I could maybe look into porting the remaining service/preferences code to ESM in my spare time as well in separate PRs.

Thanks for reaching out, totally fine with me :)
I got sick and can't currently work on this so feel free to take it away :)

**Comment by daniellandau** [comment]
Go ahead @retrixe

**Comment by andyholmes** [comment]
Closing since #1679 was completed. Thanks for getting the ball rolling on this @istvan-derda!

**Pull request closed without merging**
