### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by hugok79**
Add **pt_PT** lang code.
Portuguese (Portugal)

https://crowdin.com/project/gsconnect/pt-PT

### CODE REVIEW

**Comment by andyholmes** [comment]
Probably you'll want to add a mapping for this language to `crowdin.yml`, since it's being managed by crowdin. See `pt_BR` for an example:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/f2798d7adcc05b035f4667892b84555b69545159/crowdin.yml#L13

**Comment by andyholmes** [comment]
Probably you'll want to add a mapping for this language to `crowdin.yml`, since it's being managed by crowdin. See `pt_BR` for an example:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/f2798d7adcc05b035f4667892b84555b69545159/crowdin.yml#L13

**Comment by hugok79** [comment]
@andyholmes Done

**Comment by andyholmes** [comment]
Thanks!

**Pull request merged**
