### PR TITLE
Added tooltips to plugin menu

### PR DESCRIPTION
**Pull request by mr-kenhoff**
I recently installed GSConnect and was not quite sure what all the plugins do. 
Therefore I added tooltips that briefly describe what they do.

We can talk about the formulation of the description texts ;)

### CODE REVIEW

**Comment by mr-kenhoff** [comment]
Example:

Screenshot from 2021-01-30 17-06-05
 (Unfortunately my cursor is hidden during screenshots)

**Comment by sonnyp** [comment]
Thanks!

I agree - plugins should be more descriptive. 

While tooltips is definitely an improvement - I don't think the description should be difficult to discover.
Tooltips also don't work well on touch devices.

Would you mind turning those tooltips into `GtkLabel` with the `.subtitle` class like in GNOME Settings:

Screenshot from 2021-03-28 13-40-55
Screenshot from 2021-03-28 13-39-48

**Comment by sonnyp** [comment]
Let me know if you need assistance - happy to provide some guidance.

**Comment by sonnyp** [comment]
Looking at the code looks like passing subtitle to `new SectionRow` parameters would do the trick.

**Comment by mr-kenhoff** [comment]
Thanks for Your feedback. I will change the descriptions to subtitles.

**Comment by mr-kenhoff** [comment]
Done... Would be happy for a review.

**Comment by sonnyp** [comment]
many thanks - I made some changes - see my commits

**Comment by sonnyp** [comment]
For future reference, I think we should replace this list of plugins with something else.

Even with the descriptions - it is still not clear what each plugin does or why should I enable or disable one.

**Pull request merged**
