### PR TITLE
GSConnectManager, GSConnectPreferences: fixes for gjs 1.72

### LINKED ISSUE #1256: module.ChannelService is not a constructor
```
GSConnect: 47 (user)
GJS:       17190
Session:   wayland
OS:        Arch Linux

_loadBackends@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:33
start@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:454:14
vfunc_startup@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
vfunc_handle_local_options@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
@/home/vitalyr/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
```

### LINKED ISSUE #1277: TypeError: meta is undefined
**Describe the bug**

 GSConnect is no longer able to discover devices as of GNOME 42.beta, and phones cannot be paired.

**Steps To Reproduce:**

1. Open KDE Connect on phone
2. Notice computer name flashing in/out
3. Open GSConnect Mobile Settings on desktop
4. Preferences dialog is unable to find any phones

**Expected behavior**

Computer name holds steady on phone, phone shows up on preferences dialog.

**Screenshots**

N/A

**Support Log**

```

GSConnect: 48 (system)
GJS:       17101
Session:   x11
OS:        Ubuntu Jammy Jellyfish (development branch)
--------------------------------------------------------------------------------
Mar 08 19:16:01 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:06 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Mar 08 19:16:06 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:accept:779]: "lan://192.168.2.231:1716 (7c6e01d6-75d8-4b39-93f2-5b14398d243e)"
Mar 08 19:16:06 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/manager.js:_ensureDevice:351]: "Adding SM-A716U"
Mar 08 19:16:06 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:06 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:close:820]: "lan://192.168.2.231:1716 (7c6e01d6-75d8-4b39-93f2-5b14398d243e)"
Mar 08 19:16:08 dbus-daemon[91252]: [session uid=1000 pid=91252] Activating service name='org.gnome.gedit' requested by ':1.95' (uid=1000 pid=92896 comm="gjs /usr/share/gnome-shell/extensions/gsconnect@an" label="unconfined")
Mar 08 19:16:08 gedit[94084]: Failed to load module "xapp-gtk3-module"
Mar 08 19:16:08 gedit[94084]: Failed to load module "xapp-gtk3-module"
Mar 08 19:16:08 dbus-daemon[91252]: [session uid=1000 pid=91252] Successfully activated service 'org.gnome.gedit'
Mar 08 19:16:08 gnome-shell[91450]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x34000f8
Mar 08 19:16:11 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:16 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:21 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:26 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:31 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:36 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Mar 08 19:16:36 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:accept:779]: "lan://192.168.2.231:1716 (acbaa2d9-6e97-475a-8a57-495de13244b1)"
Mar 08 19:16:36 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/manager.js:_ensureDevice:351]: "Adding SM-A716U"
Mar 08 19:16:36 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:36 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:close:820]: "lan://192.168.2.231:1716 (acbaa2d9-6e97-475a-8a57-495de13244b1)"
Mar 08 19:16:41 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Mar 08 19:16:41 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:accept:779]: "lan://192.168.2.231:1716 (359698db-d93e-4efc-a255-5b3213386f32)"
Mar 08 19:16:41 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/manager.js:_ensureDevice:351]: "Adding SM-A716U"
Mar 08 19:16:41 gjs[92143]: JS ERROR: erich-UFocus: TypeError: meta is undefined
                            _handleIdentity@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 08 19:16:41 org.gnome.Shell.Extensions.GSConnect[92143]: [/service/backends/lan.js:close:820]: "lan://192.168.2.231:1716 (359698db-d93e-4efc-a255-5b3213386f32)"
```

**System Details (please complete the following information):**

 - **GSConnect version:** 48 + branch:wip/andyholmes/gnome42
 - **GNOME/Shell version:** 42.beta
 - **Distro/Release:** Ubuntu Jammy Jellyfish (future 22.04)

**GSConnect environment (if applicable):**

 - **Paired Device(s):** Samsung Galaxy A71 (was paired previously)
 - **KDE Connect app version:** 1.19.1
 - **Plugin(s):** N/A

**Additional Notes:**

I'm the person currently doing the package for Ubuntu

### PR DESCRIPTION
**Pull request by andyholmes**
* check for the required module properties before access when
  dynamically importing.
* mark GSConnectPreferences as implementer of Gio.ActionGroup

closes #1256
closes #1277

### CODE REVIEW

**Comment by mackdroid** [comment]
```
(gjs:14461): Gjs-CRITICAL **: 08:26:57.577: JS ERROR: TypeError: module.Metadata is undefined
@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:24:34
@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/service.js:11:16
@./gsconnect-preferences:33:18


(gjs:14461): Gjs-CRITICAL **: 08:26:57.577: Script ./gsconnect-preferences threw an exception
```
i get this while running the preferences app, and it just doesnt open from the extension manager app which i presume is because of this error

**Comment by eeickmeyer** [comment]
Per my testing, this does fix the issue.

**Comment by JingMatrix** [comment]
Maybe it is not clear what I meant, I suggest you to check `name == __init__`
in https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/af72deda94ed66f43107df4f05bcfe7247336f57/src/service/core.js#L424
and https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/af72deda94ed66f43107df4f05bcfe7247336f57/src/service/device.js#L277
.

I have a local fix, but the code style is different from you, maybe it is better for you to do the job.

**Comment by mackdroid** [comment]
also more issues
```Mar 12 15:26:22 org.gnome.Shell.Extensions.GSConnect[23355]: [/service/backends/lan.js:broadcast:413]: "Broadcasting to LAN"
Mar 12 15:26:22 org.gnome.Shell.Extensions.GSConnect[23355]: [/service/backends/lan.js:accept:779]: "lan://192.168.0.127:1716 (9f0a3e58-9e9b-4a58-b7b0-a27abc9b3ff1)"
Mar 12 15:26:22 org.gnome.Shell.Extensions.GSConnect[23355]: [/service/manager.js:_ensureDevice:351]: "Adding POCO F1"
Mar 12 15:26:22 gjs[23355]: JS ERROR: Thupc: TypeError: meta is undefined
                            _handleIdentity@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:17
                            _init@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:123:18
                            Device@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:79:4
                            _ensureDevice@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:364:22
                            _onChannel@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:216:35
                            channel@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                            _onIncomingChannel@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                            Async*@/home/thu/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Mar 12 15:26:22 org.gnome.Shell.Extensions.GSConnect[23355]: [/service/backends/lan.js:close:820]: "lan://192.168.0.127:1716 (9f0a3e58-9e9b-4a58-b7b0-a27abc9b3ff1)"
```

**Comment by eeickmeyer** [comment]
I confirm that this fixes the issues noted above.

**Comment by andyholmes** [comment]
Okay, thanks for confirming, I'll merge it in.

**Comment by jhpratt** [comment]
Hi @andyholmes, thank you for everything you do! Is there an estimated timeframe for when this (support for Gnome 42) will be released?

**Comment by andyholmes** [comment]
I should point out that this isn't exactly support for GNOME 42, just a few fixes for GJS 1.72. Other things may need to be tested and fixed before a GNOME 42 version.

Assuming that gets done, you'll have to wait for @daniellandau to re-enter the matrix to roll a release :)

**Comment by eeickmeyer** [comment]
@andyholmes I will say so far so good RE: GNOME 42, as I've been testing this on 42.beta with great results.

**Comment by jhpratt** [comment]
Okay! Thanks for the quick response. Anything I can do to assist?

**Comment by andyholmes** [comment]
> Anything I can do to assist?

If you are using the very latest GNOME 42 (ie. `gnome-shell 42.rc`), you could test to make sure there are no logged errors from the gnome-shell process during normal usage. I expect there might be some problems with [`connectObject()`](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1953), but since I don't use GSConnect anymore myself that's just a guess.

**Comment by prahal** [comment]
Just to confirm what @JingMatrix asked. Adding debug logs it is __init__that is the array item name which is undefined:
```
gjs[1055877]: JS ERROR: Error: module.ChannelService undefined for service plugins with name: __init__
		  _loadBackends@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:238:16
		  start@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:458:14
		  vfunc_startup@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:258:22
		  vfunc_handle_local_options@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:664:18
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17

gjs[1055877]: JS ERROR: Error: meta undefined for service plugins with name: __init__
		  buildIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:432:26
		  buildIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:430:15
		  get identity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:391:18
		  _onIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:340:17
		  _onIncomingIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:325:18
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
gjs[1055877]: JS ERROR: Error: meta undefined for service plugins with name: __init__
		  _handleIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:285:26
		  setChannel@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:324:18
		  _onChannel@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:225:20
		  channel@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:450:19
		  _onIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:380:18
		  async*_onIncomingIdentity@/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:325:18
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
gjs[1055933]: JS ERROR: Error: module.Metadata undefined for service plugins with name: __init__
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/device.js:21:11
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/preferences/service.js:11:16
		  @/home/prahal/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/gsconnect-preferences:31:18
```

I run a mix of Debian stable and testing (bullseye and bookworm) thus libgjs0g was upgraded to 1.72 while gjs is still 1.66.2-1. Mutter and gnome shell at 3.38.6 and your fix took care of the error I had.

**Pull request merged**
