### PR TITLE
Add GNOME 47 to version list

### LINKED ISSUE #1863: Port to GNOME 47
### Describe your request

GNOME 47.rc has been released, with the stable release set for September 18. Please update for GNOME 47 compatibility. The upgrade guide can be found here: [Port Extensions to GNOME Shell 47](https://gjs.guide/extensions/upgrading/gnome-shell-47.html)

Thanks!

### Proposed solution

_No response_

### Alternatives

_No response_

### GSConnect version

57

### Installed from

GNOME Extensions website

### GNOME Shell version

46

### Linux distribution/release

OpenSUSE Tumbleweed

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ferdnyc**
AFAICT based on https://gjs.guide/extensions/upgrading/gnome-shell-47.html, there's nothing else to do for compatibility.

Fixes #1863

I think once this and #1860 are merged, it's probably time for a release. There are several unreleased fixes GNOME 46 users will benefit from, as well.

### CODE REVIEW

**Comment by andyholmes** [comment]
I rubber-stamped the last one and it didn't go well, so I'll let someone actively using GSConnect approve this one.

**Comment by derkrasseleo** [comment]
If you provide me a build Im happy to test

**Comment by ferdnyc** [comment]
@derkrasseleo You can download a build by going to the "Checks" subtab, clicking "CI" on the left, and then clicking the "gsconnect@andyholmes.github.io" link at the bottom of the page in "Build Artifacts".

Use the Wiki "Install from Zip" instructions to upgrade.

**Comment by derkrasseleo** [comment]
> @derkrasseleo You can download a build by going to the "Checks" subtab, clicking "CI" on the left, and then clicking the "[gsconnect@andyholmes.github.io](mailto:gsconnect@andyholmes.github.io)" link at the bottom of the page in "Build Artifacts".
> 
> Use the Wiki "Install from Zip" instructions to upgrade.
> 
> (DON'T Follow the link in this comment, it's an auto-parsed link that goes nowhere.)

Thanks, seems to work fine for me on arch with Gnome 47 and Pixel 4a with KDE Connect

**Comment by ferdnyc** [comment]
Given the reported success from @derkrasseleo (and a couple of other users in #1863, who made the `metadata.json` change themselves, locally), **and** the fact that the [GNOME 47 upgrade guide](https://gjs.guide/extensions/upgrading/gnome-shell-47.html) doesn't indicate there SHOULD be anything we need to change, this one **feels** much safer than GNOME 46.

But not safe enough for me to feel right about administratively overriding the approval merge requirement, so one of @andyholmes, @sonnyp, @daniellandau still needs to give the nod before it can be merged.

(@daniellandau would also need to do the release of v58, to get it out there on e.g.o. Though I can certainly put together a release PR, if that'd help?)

**Comment by Saqr-Sayed** [comment]
@andyholmes 
we need a review here 👀

**Comment by ferdnyc** [comment]
@Saqr-Sayed 

@andyholmes [already explained](https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1866#issuecomment-2364295955) why he's not the dev to approve this, which I can respect. There are others. (Theoretically, at least. Or, worst-case scenario I **do** have the power to push this through without a review approval. I'm just very reluctant to make that particular flex.)

**Comment by ferdnyc** [comment]
Well, Ubuntu 24.10 is out for something like two weeks already, with GNOME 47, and Fedora 41 (same) is nearing readiness as well. (Decision is to be made today about a release next Tuesday; it looks like a [bug with VNC installations not accepting input](https://bugzilla.redhat.com/show_bug.cgi?id=2321249) might push things one more week, but either way it's imminent.)

So, in the interest of getting GSConnect v58 released, I'm going to push this through without secondary approval, and on my head be it if something breaks.

**Comment by ferdnyc** [comment]
And Fedora 41 was indeed designated "Go" for release on Tuesday; the couple of outstanding bugs were determined to either have a fix available, or not be serious enough to block the release. So, this was good timing.

(This isn't to imply that Fedora releases are more motivating than Ubuntu releases, when it comes to having compatible GSConnect builds available. The difference is simply that I _follow_ Fedora releases, but not Ubuntu releases, so I had no idea (until I checked earlier today) that Ubuntu 24.10 had already been released two weeks ago. Oops.)

**Pull request merged**
