### PR TITLE
WIP: GNOME 43

### LINKED ISSUE #1428: Supporting the new quick settings menu/extension
**Is your feature request related to a problem? Please describe.**
GNOME is [starting the work into changing its quick settings menu design](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2392) to a new version based on [Allan Day's mockups](https://gitlab.gnome.org/Teams/Design/os-mockups/-/tree/master/system-status/quick-settings). There's already [an extension to develop and test how it'll look and feel](https://gitlab.gnome.org/fmuellner/quick-settings-extension). And it currently [looks broken when you use it with GSConnect](https://gitlab.gnome.org/fmuellner/quick-settings-extension/-/issues/5).

**Describe the solution you'd like**
It'll be nice to start planning for what updates will be needed to support this change when the time comes it is implemented / support the extension in some shape or form, if possible.

### PR DESCRIPTION
**Pull request by fabianhjr**
This sort of works

closes #1428

### CODE REVIEW

**Comment by andyholmes** [comment]
Added a link to the issue, just so it shows up there if someone wants to help out :)

**Comment by fabianhjr** [comment]
Just an FYI, I'm a bit stump on how to upgrade so anyone else that wants to propose/try another solution feel free to go ahead.

**Comment by jbicha** [comment]
How about something like this?

```js
// Since GNOME 43: aggregateMenu -> quickSettings
if (Main.panel.statusArea.quickSettings)
    const AggregateMenu = Main.panel.statusArea.quickSettings;
else
    const AggregateMenu = Main.panel.statusArea.aggregateMenu;
```

**Comment by andyholmes** [comment]
For anyone looking to contribute to this PR, note that you will probably want to do more that just swap `aggregateMenu` with `quickSettings`, since this is a new API.

We have a short tutorial on how to use this API on gjs.guide [with examples](https://gjs.guide/extensions/topics/quick-settings.html). It may not end up being exactly compatible with GSConnect's eccentric GMenu implementation though.

**Comment by MacTavishAO** [comment]
I don't think quality of my code is good enough for a PR so I'm not creating one. Here's my commit if you want to use it while official support comes: https://github.com/MacTavishAO/gnome-shell-extension-gsconnect/commit/b50690f26bc6678056b0ba4232b532fb1ed2e07f

**Comment by fabianhjr** [comment]
Way better than what little I have been able to do. Can't currently work on this further.

**Comment by yochananmarqos** [comment]
@MacTavishAO Apparently your code quality is good enough according to @fabianhjr. Please create a new PR.

**Comment by MacTavishAO** [comment]
> @MacTavishAO Apparently your code quality is good enough according to @fabianhjr. Please create a new PR.

I'm reworking on it. I will in couple of hours.

**Comment by daniellandau** [comment]
Great!

**Comment by MacTavishAO** [comment]
PR is up. #1475

**Pull request closed without merging**
