### PR TITLE
Remove tooltip_browse_id in destory() to meet the review guidelines

### PR DESCRIPTION
**Pull request by nlpsuge**
This PR moves two global variables into Tooltip and removes tooltip_browse_id in destory() to meet the review guidelines. (https://extensions.gnome.org/review/28736)

I adopted tooltip.js in [Another Window Session Manager](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager), it's useful when the users want to know what does an icon do.

Tested on my machine, works.

Fix: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1227

### CODE REVIEW

**Review by andyholmes — CHANGES_REQUESTED** [review]
The tooltip browse mode needs a "global" of some sort to work properly. If that's not possible, browse mode should just be removed.

The way this works is to use a single variable for all widgets with tooltips. It tracks when the mouse moves between widgets quickly, so that the user doesn't have to wait the full 500ms when they're "browsing" the tooltips for information. Then when the mouse is not on any of the widgets long enough for the hover timeout to expire, the browse mode is disabled.

So the fix here is to either move the timeout ID to an ancestor widget that contains all the widgets with tooltips, or just remove it entirely.

**Comment by nlpsuge** [comment]
> The way this works is to use a single variable for all widgets with tooltips. It tracks when the mouse moves between widgets quickly, so that the user doesn't have to wait the full 500ms when they're "browsing" the tooltips for information.

Now, I understand what the 'browse mode' is.

I tested with the gsconnect released at the https://extensions.gnome.org/extension/1319/gsconnect/, seems it doesn't have the 'browse mode' actually, the code is not fully working. I hover the cursor on an icon and wait until the tip appears and then move to another icon beside it, the tip still waits 500ms to show up, if I move the cursor quickly, the tips of the icons don't show up.

I'll modify the code in my extension, and push the changes here.

I should keep the TOOLTIP_BROWSE_ID and TOOLTIP_BROWSE_MODE global variables and remove TOOLTIP_BROWSE_ID in the destroy().

**Comment by andyholmes** [comment]
[Screencast from 2022-01-09 05:57:59 PM.zip](https://github.com/GSConnect/gnome-shell-extension-gsconnect/files/7848882/Screencast.from.2022-01-09.05.57.59.PM.zip)

Here's a screencast of it working for me, is this not how it works for you? I made this the other day, but realized I'd have to ZIP it so didn't bother adding it :P

**Comment by ferdnyc** [comment]
> I made this the other day, but realized I'd have to ZIP it so didn't bother adding it :P

https://ezgif.com/, for all your video-to-GIF needs. (Animated gifs embed fine.)

**Comment by nlpsuge** [comment]
> Here's a screencast of it working for me, is this not how it works for you?

No, I tested again just now. It works well. 

BTW, I think two reasons make the previous test not right. 
1. The gap between the icons is a little bit large and the icon is a little bit small too, it's a little bit easy to move the cursor out of the icon... 
2. And another extension `Net speed Simplified` always change the network speed, and that will change the position of the panel menu, and the tool tip could disappear due to this.

**Comment by nlpsuge** [comment]
I've pushed changes into this PR. I've tested on my machine, works.

**Review by andyholmes — APPROVED** [review]

**Comment by andyholmes** [comment]
Thanks!

**Pull request merged**
